name: "Setup Swift Package Manager Cache"
description: "Setup Swift Package Manager cache for iOS builds"

runs:
  using: "composite"
  steps:
    - name: Cache Swift packages
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
