runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
