# frozen_string_literal: true

# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    fail "#{generated_xcode_build_settings_path} must exist. "\
      "If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT=(.*)/)
    return matches[1].strip if matches
  end
  fail "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. "\
    'Try deleting Generated.xcconfig, then run flutter pub get'
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  pod 'FirebaseFirestore', git: 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', tag: '10.18.0'

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods __dir__
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |build_configuration|
      # Workaround for issue not being able to build with Xcode 15.0.1
      # https://github.com/CocoaPods/CocoaPods/issues/12012#issuecomment-1653051943
      xcconfig_path = build_configuration.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, 'TOOLCHAIN_DIR')
      File.open(xcconfig_path, 'w') { |file| file << xcconfig_mod }
    end
  end
end
