# frozen_string_literal: true

import '../ios/fastlane/Fastfile'
import '../android/fastlane/Fastfile'

desc 'Flutterの依存関係をインストールします。'
lane :install_flutter_dependencies do
  Dir.chdir('../') do
    sh('flutter pub get --no-example')
  end
end

desc '自動コードを生成します。'
lane :generate do
  install_flutter_dependencies

  Dir.chdir('../') do
    sh('dart run build_runner build --delete-conflicting-outputs')
  end
end

lane :release_notes do
  analyze_commits(match: 'beta/*')
  changelog = conventional_changelog(
    format: 'plain',
    display_links: false
  )

  UI.message changelog
end

desc '最新のタグに一致するようにバージョン名を変更する'
lane :set_full_version_name_from_latest_tag do
  latest_tag_name = Dir.chdir('../') do
    sh("git describe --tags --abbrev=0 --match='beta/*'")
  end

  matched = %r{^.*/(\d+\.\d+\.\d+\+\d+)$}.match(latest_tag_name)

  full_version_name = matched[1]

  Dir.chdir('../') do
    sh("dart run cider version #{full_version_name}")
  end
end

private_lane :get_full_version_name do
  Dir.chdir('../') do
    sh('dart run cider version').chomp
  end
end
