# frozen_string_literal: true

import '../ios/fastlane/Fastfile'
import '../android/fastlane/Fastfile'

desc 'Flutterの依存関係をインストールします。'
lane :install_flutter_dependencies do
  Dir.chdir('../') do
    sh('flutter pub get --no-example')
  end
end

desc '自動コードを生成します。'
lane :generate do
  install_flutter_dependencies

  Dir.chdir('../') do
    sh('dart run build_runner build --delete-conflicting-outputs')
  end
end

lane :release_notes do
  analyze_commits(match: 'beta/*')
  changelog = conventional_changelog(
    format: 'plain',
    display_links: false
  )

  UI.message changelog
end
