# frozen_string_literal: true

default_platform(:ios)

platform :ios do
  desc 'Dev環境向けアプリをビルドします。'
  lane :build_dev do
    Dotenv.load '.env'

    apple_api_issuer_id = ENV['APPLE_API_ISSUER_ID'].to_s
    apple_api_key_id = ENV['APPLE_API_KEY_ID'].to_s

    app_store_connect_api_key_path = 'fastlane/app-store-connect-api-key.p8'
    export_options_plist_path = './ios/ExportOptions-AdHoc.plist'

    build_flutter_with_no_code_sign

    Dir.chdir('../') do
      sh(
        'set -o pipefail && '\
        'xcodebuild archive '\
        '-workspace ./ios/Runner.xcworkspace '\
        '-scheme Runner '\
        '-configuration Release '\
        '-archivePath ./build/ios/Runner.xcarchive '\
        "-authenticationKeyIssuerID '#{apple_api_issuer_id}' "\
        "-authenticationKeyID '#{apple_api_key_id}' "\
        "-authenticationKeyPath `pwd`/#{app_store_connect_api_key_path} "\
        '| xcpretty'
      )

      sh(
        'set -o pipefail && '\
        'xcodebuild -exportArchive '\
        '-archivePath ./build/ios/Runner.xcarchive '\
        '-exportPath ./build/ios/ipa '\
        "-exportOptionsPlist #{export_options_plist_path} "\
        '-allowProvisioningUpdates '\
        "-authenticationKeyIssuerID '#{apple_api_issuer_id}' "\
        "-authenticationKeyID '#{apple_api_key_id}' "\
        "-authenticationKeyPath `pwd`/#{app_store_connect_api_key_path} "\
        '| xcpretty'
      )
    end

    lane_context[SharedValues::IPA_OUTPUT_PATH] = 'build/ios/ipa/異世界Q.ipa'
  end

  desc 'Dev環境向けアプリを電子署名なしにビルドします。'
  lane :build_dev_with_no_code_sign do
    build_flutter_with_no_code_sign

    Dir.chdir('../') do
      sh(
        'set -o pipefail && '\
        'xcodebuild archive CODE_SIGNING_ALLOWED=NO '\
        '-workspace ./ios/Runner.xcworkspace '\
        '-scheme Runner '\
        '-configuration Release '\
        '-archivePath ./build/ios/Runner.xcarchive '\
        '| xcpretty'
      )
    end
  end

  desc 'Dev環境向けアプリをFirebase App Distributionにデプロイします。'
  lane :deploy_dev do
    build_dev

    firebase_app_distribution(
      app: '1:496690593871:ios:4dd3a78d4982dac605ea3a',
      service_credentials_file: 'fastlane/firebase-app-distribution-develop.json',
      groups: 'testers'
    )
  end

  private_lane :build_flutter_with_no_code_sign do |_options|
    Dir.chdir('../') do
      sh('flutter build ios --dart-define SERVER_ENV=dev --no-codesign')
    end
  end
end
