# frozen_string_literal: true

import '../../fastlane/Fastfile'

default_platform(:android)

platform :android do
  desc 'Dev環境向けアプリをビルドします。'
  lane :build_dev do
    Dir.chdir('../../') do
      sh('flutter build apk --flavor dev --dart-define-from-file dart-defines_dev.json')
    end

    lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] = '../build/app/outputs/flutter-apk/app-dev-release.apk'
  end

  desc 'Dev環境向けアプリをFirebase App Distributionにデプロイします。'
  lane :deploy_dev do
    release_notes = generate_release_notes

    build_dev

    firebase_app_distribution(
      app: '1:496690593871:android:164876b2b4d6e7da05ea3a',
      service_credentials_file: 'fastlane/firebase-app-distribution-develop.json',
      release_notes:,
      groups: 'testers'
    )
  end
end
